### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by coolieKi**

### CODE REVIEW

**Comment by b-leong** [comment]
Hi Xie Loong,
could you try the merge conflict exercise again

**Comment by coolieKi** [comment]
Hi Bryan,
So I just redo the merge conflict exercise part (the README exercise) and resubmit a PR?
Thank you!

**Comment by b-leong** [comment]
hi,
you can further commit to your own branch it should appear in this PR
if you want to resubmit it also works just remember to include your intro text file

**Comment by coolieKi** [comment]
Hi Bryan, 

I just finishing redoing it, hope it is all fine. Thank you!

**Pull request merged**
